#!/usr/bin/env bash
#
# thermal.tmux -- a thin, self-contained tmux status line.
#
# GENERATED by scripts/build.lua from lua/thermal/palette.lua -- do not edit.
#
# Structure based on niksingh710/minimal-tmux-status (MIT); colours are
# thermal's and baked in, so there is no runtime dependency. Install with tpm
# like any plugin, then `prefix + I`:
#
#     set -g @plugin 'vojoup/thermal'
#
# The bar is smoke; the heat (amber) lands only on the window and pane you are
# in -- the same move as the cursor line and search hit in the editor.

get() {
  # value of a tmux user option, or a fallback when it is unset
  local v
  v=$(tmux show-options -gqv "$1")
  [ -n "$v" ] && echo "$v" || echo "$2"
}

# ---- flavour -> baked palette --------------------------------------------
# Pick with:  set -g @thermal-tmux-flavour void   (smoky | void | ash)
flavour=$(get "@thermal-tmux-flavour" "smoky")
case "$flavour" in
    smoky) bg_d="#F6A83F" fg_d="#101014" border="#383842" sel="#2A2A32" hi="#E7E7EE" ;;
    void) bg_d="#F6A83F" fg_d="#08080A" border="#383842" sel="#24242B" hi="#E7E7EE" ;;
    ash) bg_d="#F6A83F" fg_d="#16161B" border="#383842" sel="#33333D" hi="#E7E7EE" ;;
    *) bg_d="#F6A83F" fg_d="#101014" border="#383842" sel="#2A2A32" hi="#E7E7EE" ;;
esac

# bg is the heat, fg the flavour's own smoke; override either if you want.
bg=$(get "@thermal-tmux-bg" "$bg_d")
fg=$(get "@thermal-tmux-fg" "$fg_d")

default_color="#[bg=default,fg=default,bold]"

# ---- behaviour (same option surface as the plugin this is based on) -------
use_arrow=$(get "@thermal-tmux-use-arrow" false)
larrow="$("$use_arrow" && get "@thermal-tmux-left-arrow" "")"
rarrow="$("$use_arrow" && get "@thermal-tmux-right-arrow" "")"

status=$(get "@thermal-tmux-status" "bottom")
justify=$(get "@thermal-tmux-justify" "centre")

indicator_state=$(get "@thermal-tmux-indicator" true)
indicator_str=$(get "@thermal-tmux-indicator-str" " tmux ")
indicator=$("$indicator_state" && echo "$indicator_str")

right_state=$(get "@thermal-tmux-right" true)
left_state=$(get "@thermal-tmux-left" true)

status_right=$("$right_state" && get "@thermal-tmux-status-right" "#S")
status_left=$("$left_state" && get "@thermal-tmux-status-left" "${default_color}#{?client_prefix,,${indicator}}#[bg=${bg},fg=${fg},bold]#{?client_prefix,${indicator},}${default_color}")
status_right_extra="$status_right$(get "@thermal-tmux-status-right-extra" "")"
status_left_extra="$status_left$(get "@thermal-tmux-status-left-extra" "")"

window_status_format=$(get "@thermal-tmux-window-status-format" ' #I:#{?#{m:ssh*,#{pane_current_command}},#(ps -t #{pane_tty} -o args= | grep "^ssh " | sed "s/.* //"),#W} ')

expanded_icon=$(get "@thermal-tmux-expanded-icon" '󰊓 ')
show_expanded_icon_for_all_tabs=$(get "@thermal-tmux-show-expanded-icon-for-all-tabs" false)

# ---- apply ----------------------------------------------------------------
tmux set-option -g status-position "$status"
tmux set-option -g status-style bg=default,fg=default
tmux set-option -g status-justify "$justify"

tmux set-option -g status-left "$status_left_extra"
tmux set-option -g status-right "$status_right_extra"

tmux set-option -g window-status-format "$window_status_format"
"$show_expanded_icon_for_all_tabs" && tmux set-option -g window-status-format " ${window_status_format}#{?window_zoomed_flag,${expanded_icon},}"

tmux set-option -g window-status-current-format "#[fg=${bg}]$larrow#[bg=${bg},fg=${fg}]${window_status_format}#{?window_zoomed_flag,${expanded_icon},}#[fg=${bg},bg=default]$rarrow"

# ---- surfaces the status line never touches, kept on-palette --------------
tmux set-option -g pane-border-style "fg=${border}"
tmux set-option -g pane-active-border-style "fg=${bg}"
tmux set-option -g mode-style "bg=${sel},fg=${hi}"
tmux set-option -g message-style "bg=${sel},fg=${hi}"
tmux set-option -g message-command-style "bg=${sel},fg=${hi}"
