-- thermal :: build
--
--   nvim -l scripts/build.lua
--
-- Regenerates every derived file from lua/thermal/palette.lua. Run after any
-- palette edit and after adding a flavour, then commit the result.
--
-- Uses only Neovim, which you already have on every machine this theme targets.
-- No node, no cargo, no python.

-- Absolutise first (source may be relative when invoked as `nvim -l scripts/...`),
-- then strip the script suffix to get the repo root.
local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p")
  :gsub("/scripts/build%.lua$", "")
local palette = dofile(root .. "/lua/thermal/palette.lua")
local adapter = dofile(root .. "/lua/thermal/catppuccin.lua")

local written = {}

local function write(relpath, body)
  local path = root .. "/" .. relpath
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local f = assert(io.open(path, "wb"), "cannot write " .. path)
  f:write(body)
  f:close()
  table.insert(written, relpath)
end

local GENERATED = "-- GENERATED by scripts/build.lua -- do not edit\n"

--- "#RRGGBB" -> "[R, G, B]" for Chrome theme colour arrays.
local function hex2rgb(hex)
  local r = tonumber(hex:sub(2, 3), 16)
  local g = tonumber(hex:sub(4, 5), 16)
  local b = tonumber(hex:sub(6, 7), 16)
  return ("[%d, %d, %d]"):format(r, g, b)
end

---------------------------------------------------------------- neovim ------
-- One `:colorscheme` entry point per flavour, plus the bare `thermal`.
write("colors/thermal.lua", GENERATED .. 'require("thermal").load()\n')
for _, name in ipairs(palette.order) do
  write(
    ("colors/thermal-%s.lua"):format(name),
    GENERATED .. ('require("thermal").load(%q)\n'):format(name)
  )
end

-- Stub palette modules. catppuccin's get_palette does
--   local _, palette = pcall(require, "catppuccin.palettes." .. flavour)
-- and on failure leaves `palette` as the ERROR STRING, which then reaches
-- tbl_deep_extend and crashes the compiler. So the module has to exist. It can
-- be empty: the real colours arrive via color_overrides, which is what
-- catppuccin hashes to decide when to recompile.
for _, name in ipairs(palette.order) do
  write(
    ("lua/catppuccin/palettes/thermal_%s.lua"):format(name),
    GENERATED .. "-- intentionally empty; see lua/thermal/catppuccin.lua\nreturn {}\n"
  )
end

--------------------------------------------------------------- ghostty ------
-- Save to ~/.config/ghostty/themes/ then `theme = thermal-smoky` in your config.
-- For a light/dark pair: `theme = light:thermal-ash,dark:thermal-void`.
for _, name in ipairs(palette.order) do
  local p = palette.flavours[name]
  local out = { ("# thermal-%s -- generated, see github.com/vojoup/thermal"):format(name), "" }
  for i, hex in ipairs(adapter.ansi(p)) do
    table.insert(out, ("palette = %d=%s"):format(i - 1, hex))
  end
  vim.list_extend(out, {
    "",
    "background = " .. p.bg,
    "foreground = " .. p.fg,
    "cursor-color = " .. p.amber,
    "cursor-text = " .. p.bg,
    "selection-background = " .. p.bg_sel,
    "selection-foreground = " .. p.fg_hi,
    "",
  })
  write("ghostty/thermal-" .. name, table.concat(out, "\n"))
end

write("ghostty/README.md", table.concat({
  "# thermal — Ghostty",
  "",
  "<!-- GENERATED by scripts/build.lua -- do not edit -->",
  "",
  "Symlink all flavours into place (idempotent, re-run any time):",
  "",
  "```",
  "nvim -l scripts/install.lua",
  "```",
  "",
  "Or copy one by hand:",
  "",
  "```",
  ("cp ghostty/thermal-%s ~/.config/ghostty/themes/"):format(palette.default),
  "```",
  "",
  "Then in `~/.config/ghostty/config`:",
  "",
  "```",
  ("theme = thermal-%s"):format(palette.default),
  "```",
  "",
  "Available: " .. table.concat(
    vim.tbl_map(function(n) return "`thermal-" .. n .. "`" end, palette.order), ", "),
  "",
  "For a light/dark pair Ghostty accepts:",
  "",
  "```",
  "theme = light:thermal-ash,dark:thermal-void",
  "```",
  "",
}, "\n"))

----------------------------------------------------------------- slack ------
-- Eight comma-separated values: column bg, menu hover bg, active item,
-- active item text, hover item, text, active presence, mention badge.
-- Paste into Preferences > Appearance > Custom theme.
--
-- Sidebar only -- Slack gives no way to reach the message pane, so pair with
-- Appearance > Dark or the panes won't match.
--
-- One file per flavour, containing ONLY the string, so that all of these work:
--   cat slack/thermal-void.txt | pbcopy
--   :ThermalCopy slack void
--   opening the file on GitHub and hitting copy
local slack_rows = {}
for _, name in ipairs(palette.order) do
  local p = palette.flavours[name]
  local str = table.concat({
    p.bg, -- column bg
    p.bg_alt, -- menu hover bg
    p.bg_sel, -- active item bg
    p.amber, -- active item text  <- the heat marks where you are
    p.bg_hl, -- hover item bg
    p.fg, -- text
    p.frost, -- presence dot (teal stands in for green)
    p.ember, -- mention badge
  }, ",")
  write(("slack/thermal-%s.txt"):format(name), str .. "\n")
  table.insert(slack_rows, ("| `%s` | `%s` |"):format(name, str))
end

-- Copy-friendly table, so a machine that has never cloned this repo can grab a
-- theme straight off the GitHub page.
write("slack/README.md", table.concat({
  "# thermal — Slack",
  "",
  "<!-- GENERATED by scripts/build.lua -- do not edit -->",
  "",
  "Preferences → Appearance → Custom theme, paste, save.",
  "",
  "Slack themes style the **sidebar only**. Turn on Appearance → Dark as well,",
  "or the message pane won't match.",
  "",
  "| flavour | theme string |",
  "| --- | --- |",
  table.concat(slack_rows, "\n"),
  "",
  "Order of values: column bg, menu hover bg, active item, active item text,",
  "hover item, text, active presence, mention badge.",
  "",
}, "\n"))

------------------------------------------------------------------ tmux ------
-- A thin, SELF-CONTAINED tmux plugin. Its structure is lifted from
-- niksingh710/minimal-tmux-status (MIT) -- transparent bar, centred windows,
-- prefix indicator -- but the colours are thermal's and baked in, so there is
-- no runtime dependency and nothing is pulled at build time. It installs with
-- tpm exactly like the plugin it is based on:  set -g @plugin 'vojoup/thermal'.
--
-- The bar is smoke (status-style bg=default,fg=default, so it inherits the
-- terminal). The heat -- amber -- lands only on the CURRENT window and the
-- prefix indicator: the same move as the cursor line, search hit and Slack
-- active item. Active pane border is amber too; copy-mode and the command
-- prompt take the selection colours. All three flavours are baked in and
-- picked at runtime with `set -g @thermal-tmux-flavour void`.
--
-- tpm runs root-level *.tmux files, so this lives at the repo root, executable.

-- Baked palette: one bash case arm per flavour, plus a `*` arm = the default.
local flavour_cases = {}
for _, name in ipairs(palette.order) do
  local p = palette.flavours[name]
  table.insert(flavour_cases, ("    %s) bg_d=%q fg_d=%q border=%q sel=%q hi=%q ;;")
    :format(name, p.amber, p.bg, p.border, p.bg_sel, p.fg_hi))
end
do
  local p = palette.flavours[palette.default]
  table.insert(flavour_cases, ("    *) bg_d=%q fg_d=%q border=%q sel=%q hi=%q ;;")
    :format(p.amber, p.bg, p.border, p.bg_sel, p.fg_hi))
end

local tmux_plugin = ([=[#!/usr/bin/env bash
#
# thermal.tmux -- a thin, self-contained tmux status line.
#
# GENERATED by scripts/build.lua from lua/thermal/palette.lua -- do not edit.
#
# Structure based on niksingh710/minimal-tmux-status (MIT); colours are
# thermal's and baked in, so there is no runtime dependency. Install with tpm
# like any plugin, then `prefix + I`:
#
#     set -g @plugin 'vojoup/thermal'
#
# The bar is smoke; the heat (amber) lands only on the window and pane you are
# in -- the same move as the cursor line and search hit in the editor.

get() {
  # value of a tmux user option, or a fallback when it is unset
  local v
  v=$(tmux show-options -gqv "$1")
  [ -n "$v" ] && echo "$v" || echo "$2"
}

# ---- flavour -> baked palette --------------------------------------------
# Pick with:  set -g @thermal-tmux-flavour void   (smoky | void | ash)
flavour=$(get "@thermal-tmux-flavour" "%s")
case "$flavour" in
%s
esac

# bg is the heat, fg the flavour's own smoke; override either if you want.
bg=$(get "@thermal-tmux-bg" "$bg_d")
fg=$(get "@thermal-tmux-fg" "$fg_d")

default_color="#[bg=default,fg=default,bold]"

# ---- behaviour (same option surface as the plugin this is based on) -------
use_arrow=$(get "@thermal-tmux-use-arrow" false)
larrow="$("$use_arrow" && get "@thermal-tmux-left-arrow" "")"
rarrow="$("$use_arrow" && get "@thermal-tmux-right-arrow" "")"

status=$(get "@thermal-tmux-status" "bottom")
justify=$(get "@thermal-tmux-justify" "centre")

indicator_state=$(get "@thermal-tmux-indicator" true)
indicator_str=$(get "@thermal-tmux-indicator-str" " tmux ")
indicator=$("$indicator_state" && echo "$indicator_str")

right_state=$(get "@thermal-tmux-right" true)
left_state=$(get "@thermal-tmux-left" true)

status_right=$("$right_state" && get "@thermal-tmux-status-right" "#S")
status_left=$("$left_state" && get "@thermal-tmux-status-left" "${default_color}#{?client_prefix,,${indicator}}#[bg=${bg},fg=${fg},bold]#{?client_prefix,${indicator},}${default_color}")
status_right_extra="$status_right$(get "@thermal-tmux-status-right-extra" "")"
status_left_extra="$status_left$(get "@thermal-tmux-status-left-extra" "")"

window_status_format=$(get "@thermal-tmux-window-status-format" ' #I:#{?#{m:ssh*,#{pane_current_command}},#(ps -t #{pane_tty} -o args= | grep "^ssh " | sed "s/.* //"),#W} ')

expanded_icon=$(get "@thermal-tmux-expanded-icon" '󰊓 ')
show_expanded_icon_for_all_tabs=$(get "@thermal-tmux-show-expanded-icon-for-all-tabs" false)

# ---- apply ----------------------------------------------------------------
tmux set-option -g status-position "$status"
tmux set-option -g status-style bg=default,fg=default
tmux set-option -g status-justify "$justify"

tmux set-option -g status-left "$status_left_extra"
tmux set-option -g status-right "$status_right_extra"

tmux set-option -g window-status-format "$window_status_format"
"$show_expanded_icon_for_all_tabs" && tmux set-option -g window-status-format " ${window_status_format}#{?window_zoomed_flag,${expanded_icon},}"

tmux set-option -g window-status-current-format "#[fg=${bg}]$larrow#[bg=${bg},fg=${fg}]${window_status_format}#{?window_zoomed_flag,${expanded_icon},}#[fg=${bg},bg=default]$rarrow"

# ---- surfaces the status line never touches, kept on-palette --------------
tmux set-option -g pane-border-style "fg=${border}"
tmux set-option -g pane-active-border-style "fg=${bg}"
tmux set-option -g mode-style "bg=${sel},fg=${hi}"
tmux set-option -g message-style "bg=${sel},fg=${hi}"
tmux set-option -g message-command-style "bg=${sel},fg=${hi}"
]=]):format(palette.default, table.concat(flavour_cases, "\n"))

write("thermal.tmux", tmux_plugin)
vim.fn.setfperm(root .. "/thermal.tmux", "rwxr-xr-x")

write("tmux/README.md", table.concat({
  "# thermal — tmux",
  "",
  "<!-- GENERATED by scripts/build.lua -- do not edit -->",
  "",
  "A thin, **self-contained** status line: a smoky, transparent bar with the",
  "heat landing only on the window and pane you're in. The colours are baked in,",
  "so there is no runtime dependency. Structure is based on",
  "[`niksingh710/minimal-tmux-status`](https://github.com/niksingh710/minimal-tmux-status) (MIT).",
  "",
  "## Install",
  "",
  "With [tpm](https://github.com/tmux-plugins/tpm), in `~/.tmux.conf` -- same as",
  "any plugin, then `prefix + I` to fetch it:",
  "",
  "```tmux",
  "set -g @plugin 'vojoup/thermal'",
  "run '~/.tmux/plugins/tpm/tpm'",
  "```",
  "",
  "Without tpm, point `run-shell` at the script from a clone:",
  "",
  "```tmux",
  "run-shell ~/path/to/thermal/thermal.tmux",
  "```",
  "",
  "## Flavour",
  "",
  ("Baked in: %s. Default is `%s`; switch with:"):format(
    table.concat(vim.tbl_map(function(n) return "`" .. n .. "`" end, palette.order), ", "),
    palette.default),
  "",
  "```tmux",
  "set -g @thermal-tmux-flavour void",
  "```",
  "",
  "Set it **before** `run tpm`. Pair with a thermal terminal (see `ghostty/`) so",
  "the transparent bar sits on the same smoke.",
  "",
  "## Override",
  "",
  "Colours and behaviour carry over from the plugin this is based on, under a",
  "`@thermal-tmux-` namespace:",
  "",
  "```tmux",
  "set -g @thermal-tmux-bg \"#F6A83F\"      # heat colour",
  "set -g @thermal-tmux-fg \"#101014\"      # text on the heat",
  "set -g @thermal-tmux-justify centre     # left | centre | right",
  "set -g @thermal-tmux-status bottom      # top | bottom",
  "set -g @thermal-tmux-indicator-str \" tmux \"",
  "```",
  "",
  "## Undercurl",
  "",
  "tmux flattens undercurl (and drops its colour) unless you pass the `Smulx`",
  "and `Setulc` capabilities through. Without these, the theme's curled",
  "diagnostic underlines render as flat lines inside tmux. Add to `~/.tmux.conf`:",
  "",
  "```tmux",
  "set -g default-terminal \"tmux-256color\"",
  "set -as terminal-features \",xterm-ghostty:RGB\"",
  "set -as terminal-overrides ',*:Smulx=\\E[4::%p1%dm'",
  "set -as terminal-overrides ',*:Setulc=\\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'",
  "```",
  "",
  "Then `tmux kill-server` and restart. The outer terminal must support undercurl",
  "too -- Ghostty does. Test a pane with `printf '\\e[4:3mx\\e[0m\\n'`: a curl means",
  "it's working.",
  "",
}, "\n"))

---------------------------------------------------------------- chrome ------
-- One unpacked-extension theme per flavour. Chrome themes are a manifest with a
-- `theme` block of RGB triplets: frame (the strip behind the tabs) is the
-- darkest smoke, the toolbar is a raised smoke surface (bg_hl), and the heat --
-- amber -- lands only on NTP links, the same move as the cursor line.
--
-- The toolbar is deliberately a clear step lighter than the frame. Chrome has no
-- "selected tab" colour key: multi-selected (and active) inactive tabs are
-- painted with the TOOLBAR colour, unselected tabs with the FRAME colour. If the
-- two are close, a multi-selection is invisible -- so the gap between frame
-- (bg_dark) and toolbar (bg_hl) is what makes selected tabs read.
--
-- Colours are baked in; there is no build-time or runtime dependency. Load with
-- chrome://extensions -> Developer mode -> Load unpacked, pointing at one
-- flavour's directory. See chrome/README.md.
--
-- Icons are tinted light via `tints.buttons` (HSL, lightness ~0.83) rather than
-- a colour key, which is how a dark Chrome theme keeps toolbar glyphs legible.
for _, name in ipairs(palette.order) do
  local p = palette.flavours[name]
  -- key -> palette hex. Order here is the order in the file.
  local colors = {
    { "frame", p.bg_dark },
    { "frame_inactive", p.bg_dark },
    { "frame_incognito", p.bg_dark },
    { "frame_incognito_inactive", p.bg_dark },
    { "toolbar", p.bg_hl }, -- raised surface; also the active/selected tab bg
    { "toolbar_text", p.fg },
    { "toolbar_button_icon", p.fg },
    { "tab_text", p.fg_hi },
    { "tab_background_text", p.muted },
    { "tab_background_text_inactive", p.dim },
    { "bookmark_text", p.fg },
    { "ntp_background", p.bg },
    { "ntp_text", p.fg },
    { "ntp_link", p.amber },
    { "button_background", p.bg_sel },
    { "omnibox_background", p.bg }, -- inset: darker than the raised toolbar
    { "omnibox_text", p.fg },
  }
  local color_lines = {}
  for _, kv in ipairs(colors) do
    table.insert(color_lines, ('      "%s": %s'):format(kv[1], hex2rgb(kv[2])))
  end
  local manifest = ([[{
  "manifest_version": 3,
  "version": "1.0.0",
  "name": "Thermal (%s)",
  "description": "thermal -- a dark, low-contrast theme based on the PBTfans Thermal keycap set. github.com/vojoup/thermal",
  "theme": {
    "colors": {
%s
    },
    "tints": {
      "buttons": [-1.0, -1.0, 0.83]
    },
    "properties": {
      "ntp_background_alignment": "bottom",
      "ntp_logo_alternate": 1
    }
  }
}
]]):format(name, table.concat(color_lines, ",\n"))
  write(("chrome/thermal-%s/manifest.json"):format(name), manifest)
end

write("chrome/README.md", table.concat({
  "# thermal — Chrome",
  "",
  "<!-- GENERATED by scripts/build.lua -- do not edit -->",
  "",
  "A dark browser theme: the frame behind the tabs is the darkest smoke, the",
  "toolbar is a raised smoke surface a step lighter, and the heat -- amber -- lands",
  "only on new-tab links. Colours are baked in, so there is no dependency and",
  "nothing is fetched.",
  "",
  "The toolbar being lighter than the frame is deliberate: Chrome has no",
  "\"selected tab\" colour, so it paints multi-selected (and active) tabs with the",
  "toolbar colour and unselected tabs with the frame colour. The gap between the",
  "two is what makes a multi-tab selection visible.",
  "",
  "## Install (unpacked)",
  "",
  "1. Open `chrome://extensions`.",
  "2. Turn on **Developer mode** (top right).",
  "3. **Load unpacked**, and pick one flavour's directory:",
  "",
  "```",
  ("chrome/thermal-%s"):format(palette.default),
  "```",
  "",
  "Available: " .. table.concat(
    vim.tbl_map(function(n) return "`chrome/thermal-" .. n .. "`" end, palette.order), ", ") .. ".",
  "",
  "Chrome allows one theme at a time; loading a flavour replaces the last. To",
  "remove it, `chrome://extensions` → Remove, or set another theme.",
  "",
  "Unpacked themes don't auto-update. After a palette edit and `make build`, go to",
  "`chrome://extensions` and hit the reload arrow on the theme's card.",
  "",
  "## Pack a `.crx` (optional)",
  "",
  "For a single distributable file: `chrome://extensions` → **Pack extension**,",
  ("point at `chrome/thermal-%s`, and Chrome writes a `.crx` next to it."):format(palette.default),
  "",
}, "\n"))

------------------------------------------------------------------ done ------
print(("thermal: wrote %d files from lua/thermal/palette.lua"):format(#written))
for _, r in ipairs(written) do print("  " .. r) end
